// Auto-generated by scripts/scrape_hole_coords.py.
// For each course, the lat/lng of an actual hole green from OSM,
// chosen to be the green furthest from the course centroid so
// hard mode shows a hole rather than the clubhouse area.

export interface HoleCoords {
  lat: number;
  lng: number;
  zoom: number;
}

export const HOLE_COORDS: Record<string, HoleCoords> = {
  "augusta-national-golf-club": {
    "lat": 33.49878,
    "lng": -82.02955,
    "zoom": 18
  },
  "royal-birkdale-golf-club": {
    "lat": 53.62966,
    "lng": -3.0368,
    "zoom": 18
  },
  "shinnecock-hills-golf-club": {
    "lat": 40.9013,
    "lng": -72.44409,
    "zoom": 18
  },
  "winged-foot-golf-club": {
    "lat": 40.95491,
    "lng": -73.75079,
    "zoom": 18
  },
  "valhalla-golf-club": {
    "lat": 38.24824,
    "lng": -85.47663,
    "zoom": 18
  },
  "portmarnock-golf-club": {
    "lat": 53.41581,
    "lng": -6.12017,
    "zoom": 18
  },
  "quail-hollow-club": {
    "lat": 35.1097,
    "lng": -80.84324,
    "zoom": 18
  },
  "inverness-club": {
    "lat": 41.65229,
    "lng": -83.65126,
    "zoom": 18
  },
  "crooked-stick-golf-club": {
    "lat": 39.95525,
    "lng": -86.18736,
    "zoom": 18
  },
  "cabot-links": {
    "lat": 46.22814,
    "lng": -61.31078,
    "zoom": 18
  },
  "marco-simone-golf-and-country-club": {
    "lat": 41.96822,
    "lng": 12.64023,
    "zoom": 18
  },
  "plainfield-country-club": {
    "lat": 40.59007,
    "lng": -74.37832,
    "zoom": 18
  },
  "the-australian-golf-club": {
    "lat": -33.9116,
    "lng": 151.21867,
    "zoom": 18
  }
};
