// Auto-generated by scripts/scrape_hole_coords.py.
// Per-course data for Hard mode in Holes:
//   lat/lng  — centroid for the fallback (no bbox) case
//   zoom     — fallback zoom level
//   bbox     — when present, Mapbox auto-fits the image to this rectangle
//   path     — polyline-encoded geometry tracing the hole tee->green,
//              overlaid in yellow on top of the satellite
//   holeShown — OSM-tagged hole number actually shown, when known

export interface HoleCoords {
  lat: number;
  lng: number;
  zoom: number;
  bbox?: [number, number, number, number];
  path?: string;
  holeShown: number | null;
}

export const HOLE_COORDS: Record<string, HoleCoords> = {
  "augusta-national-golf-club": {
    "lat": 33.49508,
    "lng": -82.02279,
    "zoom": 18,
    "holeShown": 12,
    "bbox": [
      -82.023468,
      33.494218,
      -82.022108,
      33.495934
    ],
    "path": "ubmkE`_ssN|EvC"
  },
  "tpc-sawgrass": {
    "lat": 30.19415,
    "lng": -81.39052,
    "zoom": 18,
    "holeShown": 17,
    "bbox": [
      -81.391167,
      30.193366,
      -81.389876,
      30.19493
    ],
    "path": "mehwDrowoN_EhC"
  },
  "muirfield": {
    "lat": 56.04445,
    "lng": -2.82102,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -2.821383,
      56.041852,
      -2.820654,
      56.047046
    ],
    "path": "wpauI|}ePzVX"
  },
  "royal-birkdale-golf-club": {
    "lat": 53.62019,
    "lng": -3.03588,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -3.03938,
      53.61823,
      -3.032266,
      53.62201
    ],
    "path": "algfIfmpQ}HkNmFiP"
  },
  "oakmont-country-club": {
    "lat": 40.52609,
    "lng": -79.82353,
    "zoom": 18,
    "holeShown": 1,
    "bbox": [
      -79.827467,
      40.525207,
      -79.82051,
      40.52685
    ],
    "path": "mcjvF|bffNmCsWaAkF"
  },
  "shinnecock-hills-golf-club": {
    "lat": 40.89623,
    "lng": -72.44096,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -72.443477,
      40.894782,
      -72.438701,
      40.898529
    ],
    "path": "u{rxFx~cyL|GyFv@m@lB}AjAoFTiA"
  },
  "winged-foot-golf-club": {
    "lat": 40.95945,
    "lng": -73.75527,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -73.756183,
      40.957301,
      -73.754116,
      40.962
    ],
    "path": "sg_yFfmdaMpMiA`FyE"
  },
  "riviera-country-club": {
    "lat": 34.04727,
    "lng": -118.50076,
    "zoom": 18,
    "holeShown": 10,
    "bbox": [
      -118.501648,
      34.045878,
      -118.500159,
      34.049068
    ],
    "path": "acynElxgrUbJqDpB@"
  },
  "medinah-country-club": {
    "lat": 41.96041,
    "lng": -88.05015,
    "zoom": 18,
    "holeShown": 17,
    "bbox": [
      -88.050604,
      41.959348,
      -88.049694,
      41.961474
    ],
    "path": "yfb_GlglxOoH|@"
  },
  "merion-golf-club": {
    "lat": 40.00337,
    "lng": -75.31316,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -75.314143,
      40.000854,
      -75.312182,
      40.006316
    ],
    "path": "}qdsFnvtjMpOkCnGcC"
  },
  "the-country-club": {
    "lat": 42.31401,
    "lng": -71.14352,
    "zoom": 18,
    "holeShown": 17,
    "bbox": [
      -71.144174,
      42.312272,
      -71.14302,
      42.316163
    ],
    "path": "ywgaGvdfqLxKlB`DcB"
  },
  "royal-aberdeen-golf-club": {
    "lat": 57.18183,
    "lng": -2.08266,
    "zoom": 18,
    "holeShown": 8,
    "bbox": [
      -2.083953,
      57.181356,
      -2.081362,
      57.182313
    ],
    "path": "qj_|ItquKdAzJ"
  },
  "portmarnock-golf-club": {
    "lat": 53.41297,
    "lng": -6.11794,
    "zoom": 18,
    "holeShown": 15,
    "bbox": [
      -6.118665,
      53.411654,
      -6.116817,
      53.413801
    ],
    "path": "u__eI~vid@kHnFIF"
  },
  "wentworth-club": {
    "lat": 51.40296,
    "lng": -0.59203,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -0.595133,
      51.400776,
      -0.58965,
      51.404787
    ],
    "path": "s{vxH`bsBxDoRrKuD"
  },
  "sunningdale-golf-club": {
    "lat": 51.3861,
    "lng": -0.62964,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -0.630285,
      51.38296,
      -0.629022,
      51.388406
    ],
    "path": "_{rxHf|yBcMdAgF~@uBsA"
  },
  "quail-hollow-club": {
    "lat": 35.1152,
    "lng": -80.84009,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -80.841277,
      35.112703,
      -80.838887,
      35.117267
    ],
    "path": "eaiuE~{klNmMtDoEhD"
  },
  "olympia-fields-country-club": {
    "lat": 41.52373,
    "lng": -87.68468,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -87.686867,
      41.521773,
      -87.681871,
      41.525874
    ],
    "path": "ilm|FxndvOdJjPrFrD"
  },
  "chambers-bay": {
    "lat": 47.2036,
    "lng": -122.57639,
    "zoom": 18,
    "holeShown": 1,
    "bbox": [
      -122.580137,
      47.202739,
      -122.572293,
      47.204327
    ],
    "path": "_jb_HhbckVkChTy@vM"
  },
  "crooked-stick-golf-club": {
    "lat": 39.94556,
    "lng": -86.19496,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -86.196586,
      39.943472,
      -86.193342,
      39.947648
    ],
    "path": "cqxrF~dbmOgR}M"
  },
  "pga-west": {
    "lat": 33.64535,
    "lng": -116.26326,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -116.264288,
      33.643443,
      -116.262211,
      33.647934
    ],
    "path": "{vjlE|xrdUnIcA`GuC`AmA"
  },
  "bandon-dunes-golf-resort": {
    "lat": 43.18682,
    "lng": -124.39976,
    "zoom": 18,
    "holeShown": 16,
    "bbox": [
      -124.4005,
      43.185244,
      -124.399125,
      43.188899
    ],
    "path": "sfrfG|xgvVdLo@rBxC"
  },
  "cabot-links": {
    "lat": 46.23866,
    "lng": -61.30165,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -61.302626,
      46.236273,
      -61.300739,
      46.241324
    ],
    "path": "ckfyGnzcuJhMlB|GrC"
  },
  "marco-simone-golf-and-country-club": {
    "lat": 41.96086,
    "lng": 12.63836,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      12.634546,
      41.959529,
      12.643458,
      41.961479
    ],
    "path": "}gb_GgedlAkEzQYrBg@~FDrB?xE"
  },
  "plainfield-country-club": {
    "lat": 40.59642,
    "lng": -74.38813,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      -74.390057,
      40.595497,
      -74.385857,
      40.597125
    ],
    "path": "}_xvF`r_eMe@zKjElE"
  },
  "the-australian-golf-club": {
    "lat": -33.91956,
    "lng": 151.21409,
    "zoom": 18,
    "holeShown": 18,
    "bbox": [
      151.213141,
      -33.922625,
      151.215368,
      -33.917026
    ],
    "path": "vj`nEee}y[kJpCmHrD{CM"
  }
};
