// Auto-generated by scripts/render_hole_svgs.py.
// Course ids that have a rendered single-hole illustration
// at public/holes/<id>.svg. Hard mode in /holes only picks
// from this set so the illustration is always available.

export const HOLE_SVG_IDS: ReadonlySet<string> = new Set([
  "augusta-national-golf-club",
  "bandon-dunes-golf-resort",
  "cabot-links",
  "chambers-bay",
  "crooked-stick-golf-club",
  "erin-hills",
  "inverness-club",
  "kingsbarns-golf-links",
  "marco-simone-golf-and-country-club",
  "medinah-country-club",
  "merion-golf-club",
  "muirfield",
  "olympia-fields-country-club",
  "pga-west",
  "plainfield-country-club",
  "portmarnock-golf-club",
  "quail-hollow-club",
  "riviera-country-club",
  "royal-aberdeen-golf-club",
  "royal-birkdale-golf-club",
  "royal-cinque-ports-golf-club",
  "shinnecock-hills-golf-club",
  "spyglass-hill-golf-course",
  "sunningdale-golf-club",
  "the-australian-golf-club",
  "the-country-club",
  "tpc-sawgrass",
  "valhalla-golf-club",
  "wentworth-club",
  "winged-foot-golf-club",
]);
