// Auto-generated by scripts/scrape_hole_coords.py.
// For each course, the lat/lng of an actual hole green from OSM,
// preferring the course's iconic hole if OSM has it tagged with a
// ref number, otherwise any other numbered hole in the 200-900m
// band from the course centroid.

export interface HoleCoords {
  lat: number;
  lng: number;
  zoom: number;
  /** OSM-tagged hole number actually shown, when known. */
  holeShown: number | null;
}

export const HOLE_COORDS: Record<string, HoleCoords> = {
  "augusta-national-golf-club": {
    "lat": 33.50447,
    "lng": -82.0235,
    "zoom": 18,
    "holeShown": 1
  },
  "tpc-sawgrass": {
    "lat": 30.20362,
    "lng": -81.39492,
    "zoom": 18,
    "holeShown": 1
  },
  "muirfield": {
    "lat": 56.04437,
    "lng": -2.82426,
    "zoom": 18,
    "holeShown": null
  },
  "royal-birkdale-golf-club": {
    "lat": 53.62218,
    "lng": -3.03639,
    "zoom": 18,
    "holeShown": null
  },
  "oakmont-country-club": {
    "lat": 40.52813,
    "lng": -79.82794,
    "zoom": 18,
    "holeShown": null
  },
  "shinnecock-hills-golf-club": {
    "lat": 40.89296,
    "lng": -72.44195,
    "zoom": 18,
    "holeShown": null
  },
  "winged-foot-golf-club": {
    "lat": 40.96117,
    "lng": -73.75541,
    "zoom": 18,
    "holeShown": null
  },
  "riviera-country-club": {
    "lat": 34.04828,
    "lng": -118.5015,
    "zoom": 18,
    "holeShown": null
  },
  "medinah-country-club": {
    "lat": 41.96119,
    "lng": -88.05028,
    "zoom": 18,
    "holeShown": 17
  },
  "valhalla-golf-club": {
    "lat": 38.23978,
    "lng": -85.46977,
    "zoom": 18,
    "holeShown": null
  },
  "merion-golf-club": {
    "lat": 39.99429,
    "lng": -75.31789,
    "zoom": 18,
    "holeShown": 3
  },
  "the-country-club": {
    "lat": 42.31143,
    "lng": -71.15052,
    "zoom": 18,
    "holeShown": null
  },
  "royal-aberdeen-golf-club": {
    "lat": 57.18165,
    "lng": -2.08365,
    "zoom": 18,
    "holeShown": 8
  },
  "portmarnock-golf-club": {
    "lat": 53.40833,
    "lng": -6.12181,
    "zoom": 18,
    "holeShown": null
  },
  "wentworth-club": {
    "lat": 51.39935,
    "lng": -0.59657,
    "zoom": 18,
    "holeShown": null
  },
  "sunningdale-golf-club": {
    "lat": 51.38852,
    "lng": -0.63401,
    "zoom": 18,
    "holeShown": null
  },
  "royal-melbourne-golf-club": {
    "lat": -37.97167,
    "lng": 145.03099,
    "zoom": 18,
    "holeShown": null
  },
  "quail-hollow-club": {
    "lat": 35.11628,
    "lng": -80.84451,
    "zoom": 18,
    "holeShown": null
  },
  "inverness-club": {
    "lat": 41.64435,
    "lng": -83.65173,
    "zoom": 18,
    "holeShown": null
  },
  "erin-hills": {
    "lat": 43.2446,
    "lng": -88.39878,
    "zoom": 18,
    "holeShown": null
  },
  "chambers-bay": {
    "lat": 47.20405,
    "lng": -122.57908,
    "zoom": 18,
    "holeShown": 1
  },
  "crooked-stick-golf-club": {
    "lat": 39.94714,
    "lng": -86.19184,
    "zoom": 18,
    "holeShown": null
  },
  "pga-west": {
    "lat": 33.64062,
    "lng": -116.26711,
    "zoom": 18,
    "holeShown": null
  },
  "spyglass-hill-golf-course": {
    "lat": 36.58352,
    "lng": -121.96451,
    "zoom": 18,
    "holeShown": 3
  },
  "cabot-links": {
    "lat": 46.23635,
    "lng": -61.30742,
    "zoom": 18,
    "holeShown": null
  },
  "kingsbarns-golf-links": {
    "lat": 56.29958,
    "lng": -2.64351,
    "zoom": 18,
    "holeShown": null
  },
  "marco-simone-golf-and-country-club": {
    "lat": 41.96289,
    "lng": 12.63633,
    "zoom": 18,
    "holeShown": null
  },
  "royal-cinque-ports-golf-club": {
    "lat": 51.241,
    "lng": 1.39993,
    "zoom": 18,
    "holeShown": null
  },
  "plainfield-country-club": {
    "lat": 40.59366,
    "lng": -74.38725,
    "zoom": 18,
    "holeShown": null
  },
  "the-australian-golf-club": {
    "lat": -33.91625,
    "lng": 151.21376,
    "zoom": 18,
    "holeShown": null
  }
};
