import type { MetadataRoute } from "next";
import { BRAND } from "@/lib/brand";

/**
 * /robots.txt — generated by Next.js from this file. Disallows the
 * paths we don't want search engines indexing:
 *
 *   /api/*       — server endpoints, including the previously open
 *                  /api/debug/projection model dumper
 *   /demo/*      — internal mock pages (cj-cup-watch, polls, insights)
 *   /promo/*     — recruiter/marketing pages with shifting content
 *   /r/*, /c/*   — single-use invite + share tokens that shouldn't
 *                  be Google-cacheable per-channel
 *   /duel/*      — ephemeral guess-the-player rooms
 *   /share/*     — shared bet/post URLs that we'd rather Google
 *                  doesn't catalog and serve back stale
 *   /replay/*    — past-tournament replay pages, only useful to
 *                  someone who already has the link
 *
 * Everything else (home, /bets, /leaderboard, /games, /sharp,
 * /tipster, /players, /[slug] tipster channels) is open to crawl.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/demo/",
          "/promo/",
          "/r/",
          "/c/",
          "/duel/",
          "/share/",
          "/replay/",
        ],
      },
    ],
    sitemap: `${BRAND.url}/sitemap.xml`,
    host: BRAND.url,
  };
}
