import type { MetadataRoute } from "next";
import { BRAND } from "@/lib/brand";
import { getSupabaseAdmin } from "@/lib/supabase/server";

/**
 * /sitemap.xml — auto-generated by Next.js from this file. Lists
 * every public surface a search engine should crawl, with a sane
 * priority + change-frequency so Google's snippet refresh stays
 * fresh on the high-value pages (the live feed) and dormant on
 * the static ones (privacy / terms).
 *
 * Public tipster channels are fetched at request time so a newly
 * created channel shows up in the next sitemap fetch without a
 * deploy. We cap at 1000 to keep the response well within the
 * 50MB / 50k-URL XML spec ceiling — past that we'd split into
 * sitemap-index form.
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const base = BRAND.url;
  const now = new Date();

  const staticEntries: MetadataRoute.Sitemap = [
    {
      url: `${base}/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 1.0,
    },
    {
      url: `${base}/bets`,
      lastModified: now,
      changeFrequency: "hourly",
      priority: 0.9,
    },
    {
      url: `${base}/leaderboard`,
      lastModified: now,
      changeFrequency: "hourly",
      priority: 0.9,
    },
    {
      url: `${base}/sharp`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${base}/games`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${base}/tipster`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${base}/pros`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.6,
    },
    {
      url: `${base}/today`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.6,
    },
    {
      url: `${base}/privacy`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${base}/terms`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];

  // Public tipster channels — only the is_public ones, since the
  // private invite-only pages shouldn't be in the public index.
  let channelEntries: MetadataRoute.Sitemap = [];
  try {
    const admin = getSupabaseAdmin();
    const { data } = await admin
      .from("channels")
      .select("slug, created_at")
      .eq("is_public", true)
      .order("created_at", { ascending: false })
      .limit(1000);
    if (data) {
      channelEntries = (data as Array<{ slug: string; created_at: string }>).map(
        (c) => ({
          url: `${base}/${c.slug}`,
          lastModified: new Date(c.created_at),
          changeFrequency: "daily" as const,
          priority: 0.5,
        }),
      );
    }
  } catch (err) {
    // Sitemap is best-effort — if Supabase blips we'd rather serve
    // the static entries than 500 the whole sitemap fetch.
    console.error("[sitemap] channels query failed", err);
  }

  return [...staticEntries, ...channelEntries];
}
