/**
 * Hand-curated category library for Pardle: Connections.
 *
 * Each entry is a single specific, discrete category — "Won the Masters",
 * "From Australia", "Surnames are common English words" — rather than
 * an attribute band like "2 or 3 majors". Discrete categories minimise
 * the overlap problem we hit in V1 (Rose AND McIlroy fit five auto-
 * generated buckets simultaneously, so the puzzle had no single
 * correct answer).
 *
 * The puzzle assembler in connections.ts picks 4 categories per day and
 * enforces strict non-overlap: every chosen golfer must appear in
 * EXACTLY ONE of the 4 selected categories' full member lists. So even
 * though Jon Rahm is in both "From Spain" and "Won the Masters", a
 * single puzzle will only use one of those categories *with* him.
 *
 * Difficulty tiers mirror NYT Connections:
 *   yellow — most obvious (country, era)
 *   green  — specific tournament wins
 *   blue   — deeper golf knowledge (world #1, FedEx Cup, captains)
 *   purple — wordplay / surface-level surname or first-name patterns
 */

import type { ConnectionsDifficulty } from "./connections-types";

export interface CategoryDef {
  id: string;
  label: string;
  difficulty: ConnectionsDifficulty;
  memberIds: string[];
}

export const CATEGORY_LIBRARY: CategoryDef[] = [
  // ─── YELLOW: country ──────────────────────────────────────────────
  {
    id: "y-australia",
    label: "From Australia",
    difficulty: "yellow",
    memberIds: [
      "adam-scott",
      "greg-norman",
      "cameron-smith",
      "jason-day",
      "marc-leishman",
      "cameron-davis",
    ],
  },
  {
    id: "y-england",
    label: "From England",
    difficulty: "yellow",
    memberIds: [
      "nick-faldo",
      "matt-fitzpatrick",
      "tyrrell-hatton",
      "sandy-lyle",
      "ian-woosnam",
      "lee-westwood",
      "aaron-rai",
    ],
  },
  {
    id: "y-spain",
    label: "From Spain",
    difficulty: "yellow",
    memberIds: [
      "jon-rahm",
      "seve-ballesteros",
      "sergio-garcía",
      "josé-maría-olazábal",
    ],
  },
  {
    id: "y-south-africa",
    label: "From South Africa",
    difficulty: "yellow",
    memberIds: [
      "gary-player",
      "ernie-els",
      "justin-rose",
      "erik-van-rooyen",
    ],
  },
  {
    id: "y-canada",
    label: "From Canada",
    difficulty: "yellow",
    memberIds: ["adam-hadwin", "mackenzie-hughes", "nick-taylor"],
  },
  {
    id: "y-south-korea",
    label: "From South Korea",
    difficulty: "yellow",
    memberIds: ["tom-kim", "sungjae-im", "si-woo-kim"],
  },
  {
    id: "y-ireland-ni",
    label: "From Ireland or Northern Ireland",
    difficulty: "yellow",
    memberIds: ["rory-mcilroy", "shane-lowry", "padraig-harrington"],
  },
  {
    id: "y-scandinavia",
    label: "From Scandinavia",
    difficulty: "yellow",
    memberIds: [
      "viktor-hovland",
      "ludvig-åberg",
      "henrik-stenson",
      "alex-norén",
      "nicolai-højgaard",
      "thorbjørn-olesen",
    ],
  },

  // ─── GREEN: specific tournament wins ──────────────────────────────
  {
    id: "g-masters",
    label: "Won the Masters",
    difficulty: "green",
    memberIds: [
      "scottie-scheffler",
      "jon-rahm",
      "dustin-johnson",
      "tiger-woods",
      "phil-mickelson",
      "bubba-watson",
      "patrick-reed",
      "jordan-spieth",
      "hideki-matsuyama",
      "fred-couples",
      "nick-faldo",
      "mark-omeara",
      "jack-nicklaus",
      "gary-player",
      "arnold-palmer",
      "josé-maría-olazábal",
      "vijay-singh",
      "tom-watson",
      "seve-ballesteros",
      "ian-woosnam",
      "sandy-lyle",
    ],
  },
  {
    id: "g-us-open",
    label: "Won the U.S. Open",
    difficulty: "green",
    memberIds: [
      "wyndham-clark",
      "dustin-johnson",
      "bryson-dechambeau",
      "brooks-koepka",
      "rory-mcilroy",
      "jon-rahm",
      "justin-rose",
      "tiger-woods",
      "jordan-spieth",
      "jack-nicklaus",
      "arnold-palmer",
      "gary-player",
      "lee-trevino",
      "tom-watson",
      "curtis-strange",
      "hale-irwin",
      "ernie-els",
      "lucas-glover",
      "webb-simpson",
      "jim-furyk",
      "matt-fitzpatrick",
    ],
  },
  {
    id: "g-open-championship",
    label: "Won the Open Championship",
    difficulty: "green",
    memberIds: [
      "rory-mcilroy",
      "jordan-spieth",
      "cameron-smith",
      "henrik-stenson",
      "brian-harman",
      "shane-lowry",
      "xander-schauffele",
      "nick-faldo",
      "tom-watson",
      "gary-player",
      "lee-trevino",
      "stewart-cink",
      "padraig-harrington",
      "john-daly",
      "sandy-lyle",
      "tom-lehman",
      "mark-calcavecchia",
      "david-duval",
      "phil-mickelson",
      "tiger-woods",
      "greg-norman",
      "ernie-els",
      "justin-leonard",
    ],
  },
  {
    id: "g-pga-championship",
    label: "Won the PGA Championship",
    difficulty: "green",
    memberIds: [
      "scottie-scheffler",
      "xander-schauffele",
      "brooks-koepka",
      "justin-thomas",
      "collin-morikawa",
      "phil-mickelson",
      "tiger-woods",
      "jason-day",
      "keegan-bradley",
      "rory-mcilroy",
      "jack-nicklaus",
      "gary-player",
      "lee-trevino",
      "padraig-harrington",
      "vijay-singh",
      "davis-love-iii",
      "john-daly",
    ],
  },
  {
    id: "g-multiple-masters",
    label: "Multiple Masters titles",
    difficulty: "green",
    memberIds: [
      "tiger-woods",
      "phil-mickelson",
      "jack-nicklaus",
      "arnold-palmer",
      "nick-faldo",
      "gary-player",
      "tom-watson",
      "seve-ballesteros",
      "bubba-watson",
      "josé-maría-olazábal",
      "scottie-scheffler",
    ],
  },
  {
    id: "g-multiple-opens",
    label: "Multiple Open Championship titles",
    difficulty: "green",
    memberIds: [
      "tom-watson",
      "nick-faldo",
      "gary-player",
      "lee-trevino",
      "padraig-harrington",
      "tiger-woods",
      "ernie-els",
      "greg-norman",
    ],
  },

  // ─── BLUE: deeper golf knowledge ──────────────────────────────────
  {
    id: "b-world-no-1",
    label: "Has held world #1",
    difficulty: "blue",
    memberIds: [
      "tiger-woods",
      "greg-norman",
      "nick-faldo",
      "fred-couples",
      "vijay-singh",
      "lee-westwood",
      "rory-mcilroy",
      "adam-scott",
      "jason-day",
      "dustin-johnson",
      "jon-rahm",
      "justin-thomas",
      "brooks-koepka",
      "scottie-scheffler",
    ],
  },
  {
    id: "b-fedex-cup",
    label: "Won the FedEx Cup",
    difficulty: "blue",
    memberIds: [
      "tiger-woods",
      "vijay-singh",
      "jim-furyk",
      "henrik-stenson",
      "jordan-spieth",
      "rory-mcilroy",
      "justin-thomas",
      "justin-rose",
      "dustin-johnson",
      "patrick-cantlay",
      "viktor-hovland",
      "scottie-scheffler",
    ],
  },
  {
    id: "b-players-championship",
    label: "Won the Players Championship",
    difficulty: "blue",
    memberIds: [
      "scottie-scheffler",
      "rory-mcilroy",
      "justin-thomas",
      "webb-simpson",
      "si-woo-kim",
      "jason-day",
      "rickie-fowler",
      "sergio-garcía",
      "phil-mickelson",
      "davis-love-iii",
      "adam-scott",
      "greg-norman",
      "tiger-woods",
      "justin-leonard",
      "sandy-lyle",
      "fred-couples",
    ],
  },
  {
    id: "b-ryder-cup-captain",
    label: "Has captained a Ryder Cup team",
    difficulty: "blue",
    memberIds: [
      "nick-faldo",
      "josé-maría-olazábal",
      "padraig-harrington",
      "davis-love-iii",
      "paul-azinger",
      "tom-watson",
      "steve-stricker",
      "jim-furyk",
      "tom-lehman",
      "colin-montgomerie",
    ],
  },
  {
    id: "b-olympic-medal",
    label: "Won an Olympic medal in golf",
    difficulty: "blue",
    memberIds: [
      "justin-rose",
      "henrik-stenson",
      "xander-schauffele",
      "hideki-matsuyama",
    ],
  },
  {
    id: "b-major-after-40",
    label: "Won a major aged 40 or older",
    difficulty: "blue",
    memberIds: [
      "phil-mickelson",
      "vijay-singh",
      "hale-irwin",
      "mark-omeara",
      "lee-trevino",
      "gary-player",
      "jack-nicklaus",
    ],
  },
  {
    id: "b-five-plus-ryder",
    label: "Five or more Ryder Cup appearances",
    difficulty: "blue",
    memberIds: [
      "rory-mcilroy",
      "phil-mickelson",
      "tiger-woods",
      "seve-ballesteros",
      "sergio-garcía",
      "nick-faldo",
      "lee-westwood",
      "bernhard-langer",
      "colin-montgomerie",
      "jim-furyk",
      "ian-woosnam",
      "jordan-spieth",
      "padraig-harrington",
      "rickie-fowler",
      "stewart-cink",
      "fred-couples",
      "arnold-palmer",
      "jack-nicklaus",
      "lee-trevino",
      "tom-watson",
    ],
  },

  // ─── PURPLE: wordplay / surname patterns ──────────────────────────
  {
    id: "p-surname-english-word",
    label: "Surname is a common English word",
    difficulty: "purple",
    memberIds: [
      "jason-day",
      "patrick-reed",
      "justin-rose",
      "gary-player",
      "curtis-strange",
      "lucas-glover",
      "ryan-fox",
      "fred-couples",
      "sam-burns",
    ],
  },
  {
    id: "p-first-name-tom",
    label: "First name is Tom",
    difficulty: "purple",
    memberIds: [
      "tom-watson",
      "tom-kim",
      "tom-hoge",
      "tom-lehman",
    ],
  },
  {
    id: "p-surname-starts-m",
    label: "Surname starts with M",
    difficulty: "purple",
    memberIds: [
      "rory-mcilroy",
      "phil-mickelson",
      "hideki-matsuyama",
      "collin-morikawa",
      "robert-macintyre",
      "maverick-mcnealy",
      "adrian-meronk",
      "keith-mitchell",
    ],
  },
  {
    id: "p-surname-starts-h",
    label: "Surname starts with H",
    difficulty: "purple",
    memberIds: [
      "viktor-hovland",
      "brian-harman",
      "tom-hoge",
      "russell-henley",
      "padraig-harrington",
      "tyrrell-hatton",
      "max-homa",
      "adam-hadwin",
      "mackenzie-hughes",
      "charley-hoffman",
      "beau-hossler",
    ],
  },
  {
    id: "p-surname-starts-k",
    label: "Surname starts with K",
    difficulty: "purple",
    memberIds: [
      "brooks-koepka",
      "tom-kim",
      "si-woo-kim",
      "kurt-kitayama",
      "kevin-kisner",
      "chris-kirk",
    ],
  },
  {
    id: "p-surname-starts-s",
    label: "Surname starts with S",
    difficulty: "purple",
    memberIds: [
      "scottie-scheffler",
      "xander-schauffele",
      "adam-scott",
      "webb-simpson",
      "jordan-spieth",
      "sepp-straka",
      "henrik-stenson",
      "vijay-singh",
      "steve-stricker",
      "curtis-strange",
      "brendan-steele",
      "adam-schenk",
      "stephan-jaeger",
    ],
  },
  {
    id: "p-four-letter-surname",
    label: "Four-letter surname",
    difficulty: "purple",
    memberIds: [
      "jason-day",
      "justin-rose",
      "ryan-fox",
      "stewart-cink",
      "chris-kirk",
      "tom-kim",
      "si-woo-kim",
      "tom-hoge",
      "aaron-rai",
      "max-homa",
    ],
  },
  {
    id: "p-first-name-justin",
    label: "First name is Justin",
    difficulty: "purple",
    memberIds: ["justin-thomas", "justin-rose", "justin-leonard"],
  },
  {
    id: "p-first-name-jordan-jon-jim",
    label: "First name starts with J",
    difficulty: "purple",
    memberIds: [
      "jordan-spieth",
      "jon-rahm",
      "justin-thomas",
      "justin-rose",
      "justin-leonard",
      "jason-day",
      "john-daly",
      "jim-furyk",
      "joel-dahmen",
      "josé-maría-olazábal",
      "joaquín-niemann",
    ],
  },
];
