"""
Augment the courses.ts file with per-course "hard mode" coordinates.

For each course in lib/data/courses.ts we query the OpenStreetMap
Overpass API for golf=green features inside the course area, then
pick the green that's *furthest from the course centroid*. That
deliberately steers hard mode away from the clubhouse (which is
typically what Wikipedia's centroid points to) and toward a hole
out on the property — making the satellite image meaningfully
different from the easy view.

The coords are written to a side-car file at lib/data/hole-coords.ts
so re-running scrape_courses.py doesn't blow them away. The Holes
page reads both and merges by course id.
"""

from __future__ import annotations

import json
import math
import re
import sys
import time
import urllib.parse
import urllib.request
from typing import Optional

OVERPASS = "https://overpass-api.de/api/interpreter"
USER_AGENT = "PardleScraper/0.1 (https://pardle.app)"


def haversine_m(a_lat: float, a_lng: float, b_lat: float, b_lng: float) -> float:
    R = 6371000.0
    p1, p2 = math.radians(a_lat), math.radians(b_lat)
    dp = math.radians(b_lat - a_lat)
    dl = math.radians(b_lng - a_lng)
    h = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * R * math.asin(math.sqrt(h))


def fetch_greens(course_name: str) -> list[tuple[float, float, Optional[str]]]:
    """Return a list of (lat, lng, ref-or-None) for every golf=green
    feature inside a named course area in OpenStreetMap."""
    query = f"""[out:json][timeout:30];
area["name"~"{course_name}"];
way(area)["golf"="green"];
out center tags;"""
    data = urllib.parse.urlencode({"data": query}).encode()
    req = urllib.request.Request(
        OVERPASS, data=data, headers={"User-Agent": USER_AGENT}
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            result = json.load(r)
    except Exception as exc:
        print(f"  overpass error: {exc}", file=sys.stderr)
        return []
    out: list[tuple[float, float, Optional[str]]] = []
    for el in result.get("elements", []):
        c = el.get("center") or {}
        if "lat" not in c or "lon" not in c:
            continue
        ref = (el.get("tags") or {}).get("ref")
        out.append((c["lat"], c["lon"], ref))
    return out


def load_courses() -> list[dict]:
    with open("lib/data/courses.ts", "r", encoding="utf-8") as f:
        text = f.read()
    m = re.search(r"export const COURSES: Course\[\] = (\[.*?\]);", text, re.DOTALL)
    if not m:
        raise RuntimeError("courses.ts not in expected format")
    return json.loads(m.group(1))


def main() -> int:
    courses = load_courses()
    print(f"Querying OSM for {len(courses)} courses...")
    coords: dict[str, dict[str, float]] = {}
    misses: list[str] = []

    for i, c in enumerate(courses):
        name = c["name"]
        print(f"[{i + 1:>3}/{len(courses)}] {name}")
        greens = fetch_greens(name)
        if not greens:
            misses.append(name)
            time.sleep(0.6)
            continue
        # Pick the green furthest from the course centroid (likely a hole
        # near the corners of the property, not the clubhouse area).
        best = max(
            greens,
            key=lambda g: haversine_m(c["lat"], c["lng"], g[0], g[1]),
        )
        lat, lng, _ref = best
        # Sanity: skip greens > 1.2km from centroid (probably mis-tagged or
        # neighbouring course).
        dist = haversine_m(c["lat"], c["lng"], lat, lng)
        if dist > 1200:
            misses.append(f"{name} (best green {dist:.0f}m away — skipping)")
            time.sleep(0.6)
            continue
        coords[c["id"]] = {
            "lat": round(lat, 5),
            "lng": round(lng, 5),
            "zoom": 18,
        }
        print(f"  -> {lat:.5f}, {lng:.5f}  ({dist:.0f}m from centroid)")
        # Polite pacing — Overpass throttles aggressively.
        time.sleep(0.6)

    print(f"\nGot coords for {len(coords)}/{len(courses)} courses")
    if misses:
        print(f"\nMisses ({len(misses)}):")
        for m in misses:
            print(f"  - {m}")

    out_path = "lib/data/hole-coords.ts"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/scrape_hole_coords.py.\n")
        f.write("// For each course, the lat/lng of an actual hole green from OSM,\n")
        f.write("// chosen to be the green furthest from the course centroid so\n")
        f.write("// hard mode shows a hole rather than the clubhouse area.\n\n")
        f.write("export interface HoleCoords {\n")
        f.write("  lat: number;\n")
        f.write("  lng: number;\n")
        f.write("  zoom: number;\n")
        f.write("}\n\n")
        f.write("export const HOLE_COORDS: Record<string, HoleCoords> = ")
        f.write(json.dumps(coords, indent=2, ensure_ascii=False))
        f.write(";\n")

    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
